
-- make id free for depth min and max
UPDATE gn_imports.dict_fields
SET order_field = order_field + 2 
WHERE order_field >= 8 AND id_theme = (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info');
-- Prise en compte des nouveaux champs, champs supprimés et renommés de la synthèse
INSERT INTO gn_imports.dict_fields (name_field, fr_label, eng_label, desc_field, type_field, 
  synthese_field, mandatory, autogenerated, nomenclature, id_theme, order_field, display, comment
) VALUES
	('depth_min', 'Profondeur min', '', '', 'integer', TRUE, FALSE, FALSE, FALSE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 8, TRUE, 
    'Correspondance champs standard: profondeurMin'
  ),
	('depth_max', 'Profondeur max', '', '', 'integer', TRUE, FALSE, FALSE, FALSE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 9, TRUE, 
    'Correspondance champs standard: profondeurMax'
  ),
	('place_name', 'Nom du lieu', '', '', 'character varying(500)', TRUE, FALSE, FALSE, TRUE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 23, TRUE, 
    'Correspondance champs standard: nomLieu'
  ),
	('precision', 'Précision du pointage (m)', '', '', 'integer', TRUE, FALSE, FALSE, TRUE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 24, TRUE, 
    'Correspondance champs standard: precisionGeometrie'
  ),	
	('cd_hab', 'Code habitat', '', '', 'integer', TRUE, FALSE, FALSE, TRUE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 25, TRUE, 
    'Correspondance champs standard: CodeHabitatValue'
  ),
	('grp_method', '', '', '', 'character varying(255)', TRUE, FALSE, FALSE, TRUE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='statement_info'), 26, TRUE, 
    'Correspondance champs standard: methodeRegroupement'
    ),

  ('additionnal_data', 'Champs additionnels', '', '', 'jsonb', TRUE, FALSE, FALSE, TRUE,
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='occurrence_sensitivity'), 16, 
    FALSE, 'Attributs additionnels'
  ), -- Ajouter un thème dédié à terme et prévoir un widget multiselect qui concatène les infos sous format jsonb ?
	('id_nomenclature_behaviour', 'Comportement', '', '', 'integer', TRUE, FALSE, FALSE, TRUE, 
    (SELECT id_theme FROM gn_imports.dict_themes WHERE name_theme='occurrence_sensitivity'), 15, 
    TRUE, 'Correspondance champs standard: occComportement'
  ),

DELETE FROM gn_imports.dict_fields
WHERE name_field IN ('id_nomenclature_obs_technique', 'sample_number_proof');

UPDATE gn_imports.dict_fields
SET name_field='id_nomenclature_obs_technique'
WHERE name_field='id_nomenclature_obs_meth';

INSERT INTO gn_imports.cor_synthese_nomenclature (mnemonique, synthese_col) VALUES
('OCC_COMPORTEMENT', 'id_nomenclature_behaviour');

UPDATE gn_imports.cor_synthese_nomenclature
SET synthese_col='id_nomenclature_obs_technique'
WHERE mnemonique='METH_OBS';

DELETE FROM gn_imports.cor_synthese_nomenclature
WHERE mnemonique='TECHNIQUE_OBS';

-- Suppression des champs sample_number_proof et obs_technique (ancien) dans les mappings existants
DELETE FROM gn_imports.t_mappings_fields
WHERE target_field IN ('id_nomenclature_obs_technique','sample_number_proof');

-- Remplacement de id_nomenclature_obs_meth vers id_nomenclature_obs_technique (nouveau) dans les mappings existants
UPDATE gn_imports.t_mappings_fields
SET target_field='id_nomenclature_obs_technique'
WHERE target_field='id_nomenclature_obs_meth';

INSERT INTO gn_imports.t_user_errors (error_type,"name",description,error_level) VALUES 
('Erreur d''incohérence','DEPTH_MIN_SUP_ALTI_MAX','profondeur min > profondeur max','ERROR')
,('Erreur de référentiel','CD_HAB_NOT_FOUND','Le cdHab indiqué n’est pas dans le référentiel HABREF ; la valeur de cdHab n’a pu être trouvée dans la version courante du référentiel.','ERROR')
;

UPDATE gn_imports.t_user_errors
SET error_type = 'Erreur d''incohérence' WHERE "name" = 'CD_NOM_NOT_FOUND';


-- rename name field id_nomenclature_bluring
UPDATE gn_imports.dict_fields 
SET fr_label = 'Floutage sur la donnée'
WHERE name_field = 'id_nomenclature_blurring';

-- Ajout de la nomenclature comportement aux mappings SINP par défaut s'ils existent
-- Intégration du mapping de valeurs SINP (labels) par défaut pour les nomenclatures de la synthèse 
INSERT INTO gn_imports.t_mappings_values (id_mapping, source_value, id_target_value)
SELECT
m.id_mapping, 
n.label_default,
n.id_nomenclature
FROM gn_imports.t_mappings m, ref_nomenclatures.t_nomenclatures n
JOIN ref_nomenclatures.bib_nomenclatures_types bnt ON bnt.id_type=n.id_type 
WHERE m.mapping_label='Nomenclatures SINP (labels)' AND bnt.mnemonique='OCC_COMPORTEMENT';


-- Intégration du mapping de valeurs SINP (codes) par défaut pour les nomenclatures de la synthèse
INSERT INTO gn_imports.t_mappings_values (id_mapping, source_value, id_target_value)
SELECT
m.id_mapping,
n.cd_nomenclature,
n.id_nomenclature
FROM gn_imports.t_mappings m, ref_nomenclatures.t_nomenclatures n
JOIN ref_nomenclatures.bib_nomenclatures_types bnt ON bnt.id_type=n.id_type 
WHERE m.mapping_label='Nomenclatures SINP (codes)' AND bnt.mnemonique='OCC_COMPORTEMENT';
